/** DO NOT EDIT THIS FILE. IT IS AUTO GENERATED BY MAVEN */
package com.cloudhopper.smpp;
public final class Version {
    private static final String TIMESTAMP="20110726-2124";
    private static final String VERSION="4.1.0";
    private static final String NAME="ch-smpp";
    private static final String VENDOR="cloudhopper";
    private static final String LONG_VERSION="4.1.0 (Build @ 20110726-2124)";
    /** Returns the library vendor such as "cloudhopper" */
    static public String getVendor() { return VENDOR; }
    /** Returns the library build timestamp such as "20110726-2124" */
    static public String getTimestamp() { return TIMESTAMP; }
    /** Returns the library name such as "ch-smpp" */
    static public String getName() { return NAME; }
    /** Returns the library version such as "4.1.0" */
    static public String getVersion() { return VERSION; }
    /** Returns a longer library version that includes the timestamp such as "4.1.0 (Build @ 20110726-2124)" */
    static public String getLongVersion() { return LONG_VERSION; }
}
